# Generated by Django 6.1.1 on 2026-09-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_id', models.CharField(blank=True, help_text='Custom identifier e.g. treat-1', max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(help_text='e.g. General Dentistry, Cosmetic Dentistry, Endodontics', max_length=100)),
                ('price_range', models.CharField(help_text='e.g. ₹500 - ₹800', max_length=100)),
                ('duration', models.CharField(help_text='e.g. 30 Mins, 45-60 Mins', max_length=50)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name or svg code', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='treatments/')),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Treatment',
                'verbose_name_plural': 'Treatments',
                'ordering': ['id'],
            },
        ),
    ]
