"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&%m2fhuk)i(ch%5m&2n(ij50j9m5$j6$4b87k_cdg!kig6wv0k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    

    # Third-party apps
    'rest_framework',
    'corsheaders',
    'drf_spectacular',
    # Local apps
    'clinic',
    'appointments',
    'blogs',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'dental_clinic_db',
        'USER': 'postgres',          # Aapka local postgres username
        'PASSWORD': 'VISHAL123', # Aapka local postgres password
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# Frontend access allow karne ke liye
CORS_ALLOW_ALL_ORIGINS = True

# Images upload (Doctor photos, treatment images) ke liye
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Dental Clinic Management API',
    'DESCRIPTION': 'API endpoints for Dental Clinic Website & Admin Portal',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}



JAZZMIN_SETTINGS = {
    "site_title": "Prism Dental Portal",
    "site_header": "Prism Dental",
    "site_brand": "Prism Dental Clinic",
    "welcome_sign": "Welcome to Prism Dental Admin",
    "copyright": "Prism Dental Clinic",

    # --- LOGO SETTINGS ---
    "site_logo": "images/logo.png",            # Sirf ye ek logo rahega
    "login_logo": None,                        # Isko None karne se duplicate hat jayega
    "site_icon": "images/logo.png",            # Favicon
    
    "custom_css": "css/custom_admin.css",

    "search_model": ["clinic.DoctorProfile", "appointments.AppointmentEnquiry"],
    "topmenu_links": [
        {"name": "Home", "url": "admin:index"},
        {"name": "API Docs", "url": "/api/docs/"},
    ],
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "clinic.DoctorProfile": "fas fa-user-md",
        "clinic.Treatment": "fas fa-tooth",
        "clinic.GalleryItem": "fas fa-images",
        "clinic.Testimonial": "fas fa-star",
        "appointments.AppointmentEnquiry": "fas fa-calendar-check",
        "blogs.BlogPost": "fas fa-newspaper",
    },
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",                    # Clean modern medical look
    "dark_mode_theme": None,
    "navbar": "navbar-dark navbar-primary",
    "sidebar": "sidebar-dark-primary",    # Deep navy sidebar
    "accent": "accent-info",              # Cyan/Teal accent matching the logo
    "brand_colour": "navbar-primary",
    "body_small_text": False,
    "sidebar_nav_small_text": False,
    "sidebar_nav_child_indent": True,
}