# Generated by Django 6.1.1 on 2026-09-10 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='SmileCare Dental Clinic', max_length=200)),
                ('tagline', models.CharField(blank=True, help_text='e.g. Your Smile, Our Priority', max_length=255, null=True)),
                ('phone_number', models.CharField(help_text='Click-to-call phone number', max_length=20)),
                ('whatsapp_number', models.CharField(help_text='Format with country code: e.g. 919876543210', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('opening_hours', models.CharField(help_text='e.g. Mon - Sat: 9:00 AM - 8:00 PM, Sunday: Closed', max_length=255)),
                ('google_maps_embed_url', models.TextField(help_text='Google Maps iframe embed URL')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic/branding/')),
            ],
            options={
                'verbose_name': 'Clinic Information',
                'verbose_name_plural': 'Clinic Information',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('qualification', models.CharField(help_text='e.g. BDS, MDS - Conservative Dentistry', max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=5)),
                ('specialization', models.CharField(help_text='e.g. Cosmetic Dentist, Root Canal Specialist', max_length=255)),
                ('certifications', models.CharField(blank=True, max_length=300, null=True)),
                ('bio', models.TextField(help_text='Detailed professional introduction')),
                ('photo', models.ImageField(upload_to='clinic/doctors/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on website')),
            ],
            options={
                'verbose_name': 'Doctor Profile',
                'verbose_name_plural': 'Doctor Profiles',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('CLINIC', 'Clinic Photos'), ('EQUIPMENT', 'Modern Equipment'), ('BEFORE_AFTER', 'Treatment Before & After')], default='CLINIC', max_length=20)),
                ('image', models.ImageField(upload_to='clinic/gallery/')),
                ('patient_consent_verified', models.BooleanField(default=True, help_text='Ensure patient consent was obtained if using before/after pictures')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='Benefits and details of equipment/service')),
                ('image', models.ImageField(blank=True, null=True, upload_to='clinic/technology/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Technology & Service',
                'verbose_name_plural': 'Technology & Services',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('category', models.CharField(default='General', help_text='e.g. Cosmetic, Orthodontics, Surgery', max_length=100)),
                ('short_description', models.TextField(help_text='Used in homepage treatment cards', max_length=350)),
                ('full_details', models.TextField(help_text='Detailed explanation of treatment, procedure, benefits')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='clinic/treatments/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Treatment',
                'verbose_name_plural': 'Treatments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MAIN_ADMIN', 'Main Admin (Doctor/Owner)'), ('SUB_ADMIN', 'Sub Admin (Clinic Manager/Receptionist)'), ('DOCTOR', 'Doctor')], default='SUB_ADMIN', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('assigned_branch', models.CharField(default='Main Branch', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sub_admins', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(help_text='Patient name or initials', max_length=150)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating out of 5')),
                ('review_text', models.TextField()),
                ('google_review_link', models.URLField(blank=True, help_text='Link to original Google Review', null=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Only approved reviews will show on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('treatment_taken', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='clinic.treatment')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
