# Generated by Django 6.1.1 on 2026-09-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(blank=True, help_text='Reference ID e.g. APT-1001', max_length=30, unique=True)),
                ('patient_name', models.CharField(help_text='Full Name of the patient', max_length=150)),
                ('phone', models.CharField(help_text='Primary contact phone/mobile number', max_length=30)),
                ('email', models.EmailField(blank=True, help_text='Optional email address', max_length=254, null=True)),
                ('treatment', models.CharField(help_text='Selected dental service or procedure', max_length=200)),
                ('doctor', models.CharField(blank=True, default='Any Available Specialist', max_length=150)),
                ('date', models.DateField(help_text='Preferred consultation date')),
                ('time_slot', models.CharField(help_text='Preferred time slot e.g. 10:30 AM - 12:00 PM', max_length=50)),
                ('status', models.CharField(choices=[('New', 'New Enquiry'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid in Full'), ('Partial', 'Partial Advance')], default='Pending', max_length=20)),
                ('payment_amount', models.CharField(blank=True, default='₹800', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Symptoms, clinical notes or patient requests')),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('online_consultation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
