# Generated by Django 6.1.1 on 2026-09-10 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Query',
                'verbose_name_plural': 'Contact Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(help_text='10-digit mobile number', max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(help_text='e.g. 10:30 AM ya Morning Slot', max_length=50)),
                ('message', models.TextField(blank=True, help_text='Patient ki dental problem ya remarks', null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20)),
                ('internal_notes', models.TextField(blank=True, help_text='Doctor/Staff ke liye internal notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinic.treatment')),
            ],
            options={
                'verbose_name': 'Appointment Enquiry',
                'verbose_name_plural': 'Appointment Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
