# Generated by Django 6.1.1 on 2026-09-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(blank=True, help_text='Custom identifier e.g. case-1', max_length=100, null=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(help_text='e.g. transformations, clinic, treatments, patients, Smile Makeover, Orthodontics', max_length=100)),
                ('doctor', models.CharField(blank=True, max_length=150)),
                ('patient_consent', models.BooleanField(default=True, help_text='Mandatory per medical guidelines (docs.pdf Section 1.5): patient permission before publishing')),
                ('consent_ref', models.CharField(blank=True, help_text='e.g. CONSENT-SIGNED-2025-089', max_length=100)),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='gallery/before/')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='gallery/after/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('before_url', models.CharField(blank=True, max_length=500)),
                ('after_url', models.CharField(blank=True, max_length=500)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('treatment_duration', models.CharField(blank=True, help_text='e.g. 2 Appointments (7 Days)', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Case',
                'verbose_name_plural': 'Gallery Cases',
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]
