# Generated by Django 6.1.1 on 2026-09-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='Prism Dental Clinic', max_length=200)),
                ('tagline', models.CharField(default='Healthy Smile, Happy Life', max_length=200)),
                ('phone', models.CharField(default='+91 82392 39249', max_length=50)),
                ('whatsapp', models.CharField(default='8239239249', max_length=50)),
                ('emergency_helpline', models.CharField(default='+91 82392 39249', max_length=50)),
                ('email', models.EmailField(default='contact.prisminfotech@gmail.com', max_length=254)),
                ('address', models.TextField(default='Near Bus Stand, Ramganj Mandi, Kota, Rajasthan - 326519')),
                ('working_hours_weekday', models.CharField(default='09:00 AM - 08:00 PM (Mon - Sat)', max_length=100)),
                ('working_hours_sunday', models.CharField(default='10:00 AM - 02:00 PM (Sun)', max_length=100)),
                ('whatsapp_booking_template', models.TextField(blank=True, default='Hello {PATIENT_NAME}, thank you for choosing Prism Dental Clinic! Your appointment for {TREATMENT} with {DOCTOR} is confirmed for {DATE} at {TIME_SLOT}. Location: Ramganjmandi, Kota, Rajasthan. Please arrive 10 minutes prior.')),
                ('whatsapp_reminder_template', models.TextField(blank=True, default='Reminder from Prism Dental Clinic: Hi {PATIENT_NAME}, you have an upcoming consultation tomorrow ({DATE}) at {TIME_SLOT} with {DOCTOR}. If you need to reschedule, reply to this message.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic Settings',
                'verbose_name_plural': 'Clinic Settings',
            },
        ),
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_id', models.CharField(blank=True, help_text='e.g. ENQ-201', max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('service', models.CharField(blank=True, help_text='Service of interest', max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New Enquiry'), ('Responded', 'Responded'), ('Archived', 'Archived')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Enquiry',
                'verbose_name_plural': 'Contact Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
