# Generated by Django 6.1.1 on 2026-09-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(blank=True, help_text='Custom identifier e.g. dr-rohan-mehta', max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(default='Dental Surgeon', help_text='e.g. Chief Dentist & Founder', max_length=150)),
                ('specialty', models.CharField(help_text='e.g. Prosthodontist & Implantologist', max_length=200)),
                ('degree', models.CharField(default='BDS, MDS', max_length=150)),
                ('experience', models.CharField(default='5+ Years', max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('languages', models.JSONField(blank=True, default=list, help_text='List of languages spoken')),
                ('available', models.BooleanField(default=True, help_text='Current duty/availability status')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=700.0, max_digits=10)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('photo_url', models.CharField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True)),
                ('today_appointments', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['id'],
            },
        ),
    ]
