# Generated by Django 6.1.1 on 2026-09-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.CharField(blank=True, help_text='e.g. blog-1', max_length=100, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(help_text='e.g. General Dentistry, Oral Health, Treatment Guide', max_length=100)),
                ('author', models.CharField(default='Dr. Rohan Mehta', max_length=150)),
                ('author_role', models.CharField(blank=True, default='Dental Surgeon', max_length=150)),
                ('read_time', models.CharField(default='5 min read', max_length=50)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Array of tag strings')),
                ('excerpt', models.TextField(blank=True, help_text='Short teaser summary')),
                ('content', models.TextField(blank=True, help_text='Full article body (HTML or Markdown or paragraphs)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('cover_image_url', models.CharField(blank=True, max_length=500)),
                ('published_date', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
