# Generated by Django 6.1.1 on 2026-09-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('treatment', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, help_text='e.g. Whitening, Implants, Orthodontics, Root Canal, Cosmetic, General', max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating 1 to 5')),
                ('comment', models.TextField(help_text='Patient testimonial review quote')),
                ('review_date', models.CharField(blank=True, max_length=50)),
                ('doctor', models.CharField(blank=True, max_length=150)),
                ('highlight', models.CharField(blank=True, help_text='Key result highlight badge e.g. 3 Shades Whiter in 45 Mins', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('verified', models.BooleanField(default=True, help_text='Verified patient badge')),
                ('featured', models.BooleanField(default=False, help_text='Feature on home page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]
